---
language: python
python:
  - '2.7'
sudo: required
services:
  - docker
env:
  md_ignore: R1
addons:
  apt:
    packages:
      - ruby-full
before_install:
install:
  - pip install -r requirements.txt
  - bundle install
before_script:
  - >
      for file in `find . -maxdepth 2 -name "*.md"` ;  do
      markdownlint --ignore $md_ignore $file ;
      done
script:
  -  ansible-galaxy init -f --role-skeleton=egi-galaxy-template test-role
  - inspec exec -b local ansible-fashion-police
  - cd test-role
  - molecule init scenario -r test-role
  - molecule test
after_success:
after_failure:
before_deploy:
deploy:
after_deploy:
after_script:
notifications:
  slack:
    secure: S5s1uMaEu6FZjovKwBU43GKoZsdAFvUhvbnfGKfymSZxVNGNmPpWkpPiTeH5keo3lMEorU5KQgPKPwoXTIZnHv687kpW+KUIqfZw2Z2NVkrfJ8gZxj2oOqbCCXl+JHeJSziQ/siUDJriadfqt7tmXWLvlw19G+Na5mBevqFxtFpQ6HrCapEpOkarcmJbOONxlk8zVKcjCh06sZYtxdiRK67VAsoQWINnAmp1sFNjwoaSCF1ATayk76XGsObUmS3/ku51a5gyPzWmZzc0biXk+XGjeB2BRwur/uzQa2UQmlUBrhYLMzTDvUse2oR/i6ae2/vT90wBxMk/dY+OF5rO0v0i9sZMdl102F/CgAGlPPQ/aTXVI6pVnL+5D/X0OqaJ+CR4EhUVjXNbvdkg1wm7EZQbWpKP1P3Hf3YnzPTwllZCX/NNz/5vtJjjedm161EtKi0WgbcKt9UTmINCfGDAg/2vmVm3bBUqdrdGlX5VUszhlGxGobTAeTHyoLgY0+qjm6Gj8f/VTsoq+jIRhZ0Mh1c/eTH179RGCNhwhL3H7QEMarbFx+D1Lhh5MN5bNyJ8Q6Mt7GaRB57OHRpLSZSAgbR/HGkaKF8gyA6zxUh2yxsIRJw0KvX4PPSYJbcyR8fa96I1xcRFNwC1XmP4WzFu2ocGBERK+bHZSqkT2T7DSCw=
