language: python
python:
- '2.7'
sudo: required
services:
- docker
env:
  global:
  - MD_IGNORE=R1
  - TEST_ROLE_PATH=ansible-role-test/
  - GITHUB_REPO=$TRAVIS_REPO_SLUG
  - RUBOCOP_OPTS=--fail-level=error
addons:
  apt:
    packages:
    - ruby-full
before_install:
install:
- pip install -r requirements.txt
- bundle install --binstubs --verbose --path $(pwd)/vendor/bundle
before_script:
- for file in `find . -maxdepth 2 -name "*.md"` ;  do markdownlint --ignore $MD_IGNORE
  $file ; done
- docker pull centos:7
script:
- ansible-galaxy init -f --role-skeleton=egi-galaxy-template $TEST_ROLE_PATH
- echo $PATH
- where inspec
- which inspec
- bundle doctor
- bundle info inspec
- find /home/travis -name inspec
- find /home/travis/build/EGI-Foundation/ansible-style-guide/vendor/bundle/ -name inspec
- bundle exec inspec supermarket exec brucellino/ansible-fashion-police --controls=Travis Meta
  'Ansible Skeleton Directories' 'Ansible YAML main files'
- bundle exec inspec supermarket exec brucellino/ansible-fashion-police --controls=Travis Meta
  'Ansible Skeleton Directories' 'Ansible YAML main files'
- inspec supermarket exec brucellino/ansible-fashion-police --controls=Travis Meta
  'Ansible Skeleton Directories' 'Ansible YAML main files'
- ls -lR /home/travis/.rvm/gems/ruby-2.4.1/gems/inspec-4.3.2/
- ls -lR /home/travis/build/EGI-Foundation/ansible-style-guide/vendor/bundle/
- cd $TEST_ROLE_PATH
- molecule init scenario -r $TEST_ROLE_PATH
- molecule lint
- molecule dependency
- molecule syntax
- molecule create
- molecule prepare
- molecule converge
- molecule idempotence
- molecule verify
- molecule destroy
after_success:
after_failure:
before_deploy:
deploy:
after_deploy:
after_script:
notifications:
  slack:
    secure: S5s1uMaEu6FZjovKwBU43GKoZsdAFvUhvbnfGKfymSZxVNGNmPpWkpPiTeH5keo3lMEorU5KQgPKPwoXTIZnHv687kpW+KUIqfZw2Z2NVkrfJ8gZxj2oOqbCCXl+JHeJSziQ/siUDJriadfqt7tmXWLvlw19G+Na5mBevqFxtFpQ6HrCapEpOkarcmJbOONxlk8zVKcjCh06sZYtxdiRK67VAsoQWINnAmp1sFNjwoaSCF1ATayk76XGsObUmS3/ku51a5gyPzWmZzc0biXk+XGjeB2BRwur/uzQa2UQmlUBrhYLMzTDvUse2oR/i6ae2/vT90wBxMk/dY+OF5rO0v0i9sZMdl102F/CgAGlPPQ/aTXVI6pVnL+5D/X0OqaJ+CR4EhUVjXNbvdkg1wm7EZQbWpKP1P3Hf3YnzPTwllZCX/NNz/5vtJjjedm161EtKi0WgbcKt9UTmINCfGDAg/2vmVm3bBUqdrdGlX5VUszhlGxGobTAeTHyoLgY0+qjm6Gj8f/VTsoq+jIRhZ0Mh1c/eTH179RGCNhwhL3H7QEMarbFx+D1Lhh5MN5bNyJ8Q6Mt7GaRB57OHRpLSZSAgbR/HGkaKF8gyA6zxUh2yxsIRJw0KvX4PPSYJbcyR8fa96I1xcRFNwC1XmP4WzFu2ocGBERK+bHZSqkT2T7DSCw=
