---
language: python
python:
  - '2.7'
  - '3.6'
sudo: required
services:
  - docker
env:
  global:
    - MD_IGNORE="R1"
    - TEST_ROLE_PATH="ansible-role-test/"
    - GITHUB_REPO=$TRAVIS_REPO_SLUG
    - RUBOCOP_OPTS="--fail-level=error"
    - secure: L6XBIPdTMVxsZ7YbHpbyPay+0mCvOdfa0FcMosK2Rn7TjzRb5GH8lfuHcJ/pSJ3Mg9B740LfiiE/pazwSsrRCzdUsbBfR2VMJepoJjD2TAX89Lcm0AdzElHOQu62CFMg6/tF4RiCaAEQRxntN/TC6JrZugtb4p/Ap79Ozosf76fKrnegcMXeB7HXoMEQzsWRc2SsWALy38DZ9iMHHRMcO/dhCt5/FW8wG6tc0f5cwZRWt9tE73MY6Bxe3yMri0KUR2pDgijOVpzdQJgKPx6omuGIve7SrztywXXA9XX0wB5OAfK++9ToJYoBcx1+W9evdemzfyKNwLZZijWFj2Ql8EHXpBsyZNbXIRa/tLHLbF7UnRbho+124vl7KTxFFw0RQWHkQ/SeLU4Gr0yONnhSZok/Rv/0/iXMojV1SwVwM9wDyhpYubKnDzbanveeQ5M/cjcu8egNS/uvE4LfDDBFRpbcMngPKMVPBK1j/3GadWezkOIyqpRybl8wrC9b0+4wfBM01EkiodjZoRSNYNAapt714E20MxgH7HANMVzVU9Yg6vxQQRU+aq2JhaGqdgL/gKKZgQPFazCE0WLUwT+GTBd81A9wVUPhhAN7cPbHJFv1rNcpwiJrlWPBjqQTqhDjP+u5KqZ1MYLXH7dM65YGypMRJhEnhvQlGO+iZWGb9ik=
addons:
  apt:
    packages:
      - ruby-full
before_install:
install:
  - pip install -r requirements.txt
  - bundle install
before_script:
  - for file in `find . -maxdepth 2 -name "*.md"` ;  do markdownlint --ignore $MD_IGNORE
    $file ; done
script:
  - ansible-galaxy init -f --role-skeleton=egi-galaxy-template $TEST_ROLE_PATH
  - inspec supermarket exec brucellino/ansible-fashion-police -b local
  - cd $TEST_ROLE_PATH
  - molecule init scenario -r $TEST_ROLE_PATH
  - molecule test
after_success:
after_failure:
before_deploy:
deploy:
after_deploy:
after_script:
notifications:
  slack:
    secure: S5s1uMaEu6FZjovKwBU43GKoZsdAFvUhvbnfGKfymSZxVNGNmPpWkpPiTeH5keo3lMEorU5KQgPKPwoXTIZnHv687kpW+KUIqfZw2Z2NVkrfJ8gZxj2oOqbCCXl+JHeJSziQ/siUDJriadfqt7tmXWLvlw19G+Na5mBevqFxtFpQ6HrCapEpOkarcmJbOONxlk8zVKcjCh06sZYtxdiRK67VAsoQWINnAmp1sFNjwoaSCF1ATayk76XGsObUmS3/ku51a5gyPzWmZzc0biXk+XGjeB2BRwur/uzQa2UQmlUBrhYLMzTDvUse2oR/i6ae2/vT90wBxMk/dY+OF5rO0v0i9sZMdl102F/CgAGlPPQ/aTXVI6pVnL+5D/X0OqaJ+CR4EhUVjXNbvdkg1wm7EZQbWpKP1P3Hf3YnzPTwllZCX/NNz/5vtJjjedm161EtKi0WgbcKt9UTmINCfGDAg/2vmVm3bBUqdrdGlX5VUszhlGxGobTAeTHyoLgY0+qjm6Gj8f/VTsoq+jIRhZ0Mh1c/eTH179RGCNhwhL3H7QEMarbFx+D1Lhh5MN5bNyJ8Q6Mt7GaRB57OHRpLSZSAgbR/HGkaKF8gyA6zxUh2yxsIRJw0KvX4PPSYJbcyR8fa96I1xcRFNwC1XmP4WzFu2ocGBERK+bHZSqkT2T7DSCw=
