---
# Travis template for an EGI-styled role
language: python
python:
  - '2.7'
sudo: required
services:
  - docker
env:
  md_ignore: R1  # Which markdownlint rules to ignore
addons:
  apt:
    packages:
      - ruby-full
before_install:
install: # Install the things you'll need to be stylish
  - git clone https://github.com/EGI-Foundation/ansible-style-guide
  - cd ansible-style-guide 
  - pip install -r requirements.txt  # The packages necessary for running the tests.
  - bundle install
before_script:
  - > # Lint all the markdown files
      for file in `find . -maxdepth 2 -name "*.md"` ;  do
      markdownlint --ignore $md_ignore $file ;
      done
script:
  - molecule test
  - cd $TRAVIS_BUILD_DIR
after_success:
after_failure:
before_deploy:
deploy:
after_deploy:
after_script:
# Add your notifications here.
# Use travis encrypt to add api tokens.
notifications:
#   slack:
#     secure:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/